### ISSUE TITLE
24V directly connected to Arduino 

### ISSUE THREAD

**Issue by pixelcrash** [tigoe/LightProjects#1]
[The Image](https://tigoe.github.io/LightProjects/img/12VDC_LED_TIP120_circuit_bb.png) shows that the 24V/12V power supply is connected directly to the Arduino.  Will this not fry the Arduino?

**Comment by tigoe** [comment]
The 12V is not connected to the Arduino, it's connected to the strip lights. The ground is connected to the Arduino's ground.
